// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu-Mqn1SLV8tr5us-lDgah-K7xR8Od2yQ',
    appId: '1:409363777864:web:989f62633c0df43e18cb7d',
    messagingSenderId: '409363777864',
    projectId: 'toxikon-e4395',
    authDomain: 'toxikon-e4395.firebaseapp.com',
    storageBucket: 'toxikon-e4395.appspot.com',
    measurementId: 'G-2H0BNX9Y4J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDshJ-LZ4pCKMa9NsNIv8hUuSf8Gp0LezA',
    appId: '1:409363777864:android:ae49e0e8fb93c28e18cb7d',
    messagingSenderId: '409363777864',
    projectId: 'toxikon-e4395',
    storageBucket: 'toxikon-e4395.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6WYGt32J6w4vp35jUSZOTF3KbC8XfcCw',
    appId: '1:409363777864:ios:da9953a8d6a0fa9418cb7d',
    messagingSenderId: '409363777864',
    projectId: 'toxikon-e4395',
    storageBucket: 'toxikon-e4395.appspot.com',
    iosBundleId: 'com.example.sportsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6WYGt32J6w4vp35jUSZOTF3KbC8XfcCw',
    appId: '1:409363777864:ios:9ca9f8c0f443944a18cb7d',
    messagingSenderId: '409363777864',
    projectId: 'toxikon-e4395',
    storageBucket: 'toxikon-e4395.appspot.com',
    iosBundleId: 'com.example.sportsApp.RunnerTests',
  );
}
